FROM postgres:latest

ENV POSTGRES_ROOT_PASSWORD=azerty
ENV POSTGRES_DATABASE=mabase
ENV POSTGRES_USER=stephane
ENV POSTGRES_PASSWORD=12345

RUN apt-get update
RUN apt-get install -y --fix-missing openssh-client openssh-server