# Image de base
FROM postgres:17

# Mot de passe ROOT du serveur de base de données
ENV POSTGRES_ROOT_PASSWORD=azerty

# Nom de la base de données qui sera créée au 1er démarrage du conteneur
ENV POSTGRES_DATABASE=mabase

# Nom d'utilisateur pour se connecter à la base de données
ENV POSTGRES_USER=stephane

# Mot de passe pour se connecter à la base de données
ENV POSTGRES_PASSWORD=12345


