#Image de base
FROM mysql:8.4.6

# Mot de passe ROOT du serveur de base de données
ENV MYSQL_ROOT_PASSWORD=aazert

# Nom de la base de données qui sera créée au 1er démarrage du conteneur
ENV MYSQL_DATABASE=databasesql

# Nom d'utilisateur pour se connecter à la base de données
ENV MYSQL_USER=nobert

# Mot de passe pour se connecter à la base de données
ENV MYSQL_PASSWORD=12345

VOLUME ["/data", "/data_numero2"]

