# image pour Microsoft SQL SERVER 2019
FROM mcr.microsoft.com/mssql/server:2019-latest

# Obligatoire, accepter la licence
ENV ACCEPT_EULA=Y

# Mot de passe administrateur 
# respecter la stratégie de mot de passe (8 caractères, au moins 1 majuscule, 1 minuscule, 
# 1 chiffres et 1 caractère spécial)
ENV MSSQL_SA_PASSWORD=Azerty!01

